# Generated by Django 4.2.28 on 2026-02-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='Type of action (e.g., PROPOSAL_SUBMITTED, REVIEW_ASSIGNED)', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('approved_grant_amount', models.DecimalField(decimal_places=2, help_text='Final approved grant amount', max_digits=12)),
                ('final_remarks', models.TextField(help_text='Final remarks from SRC Chair')),
            ],
            options={
                'verbose_name': 'Final Decision',
                'verbose_name_plural': 'Final Decisions',
            },
        ),
        migrations.CreateModel(
            name='GrantCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., CTRG 2025-2026', max_length=100)),
                ('year', models.CharField(help_text='e.g., 2025-2026', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stage1_review_start_date', models.DateField(blank=True, help_text='Optional Stage 1 review start date', null=True)),
                ('stage1_review_end_date', models.DateField(blank=True, help_text='Optional Stage 1 review end date', null=True)),
                ('stage2_review_start_date', models.DateField(blank=True, help_text='Stage 2 review start date', null=True)),
                ('stage2_review_end_date', models.DateField(blank=True, help_text='Stage 2 review end date', null=True)),
                ('revision_window_days', models.IntegerField(default=7, help_text='Number of days for revision after tentative acceptance')),
                ('acceptance_threshold', models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum percentage score for acceptance', max_digits=5)),
                ('max_reviewers_per_proposal', models.IntegerField(default=2, help_text='Maximum number of reviewers (1-4)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Grant Cycle',
                'verbose_name_plural': 'Grant Cycles',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_code', models.CharField(editable=False, help_text='Auto-generated unique code (e.g., CTRG-2025-001)', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('pi_name', models.CharField(help_text='Principal Investigator name', max_length=255)),
                ('pi_department', models.CharField(max_length=255)),
                ('pi_email', models.EmailField(max_length=254)),
                ('co_investigators', models.TextField(blank=True, help_text='Comma-separated list of co-investigators')),
                ('fund_requested', models.DecimalField(decimal_places=2, help_text='Amount of funding requested', max_digits=12)),
                ('proposal_file', models.FileField(blank=True, help_text='Full research proposal (PDF)', null=True, upload_to='proposals/')),
                ('application_template_file', models.FileField(blank=True, help_text='Research Grant Application Template (PDF/Word)', null=True, upload_to='proposals/templates/')),
                ('revised_proposal_file', models.FileField(blank=True, help_text='Revised proposal after Stage 1 review', null=True, upload_to='proposals/revisions/')),
                ('response_to_reviewers_file', models.FileField(blank=True, help_text='Optional response to reviewer comments', null=True, upload_to='proposals/responses/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_STAGE_1_REVIEW', 'Under Stage 1 Review'), ('STAGE_1_REJECTED', 'Stage 1 Rejected'), ('ACCEPTED_NO_CORRECTIONS', 'Accepted (No Corrections Required)'), ('TENTATIVELY_ACCEPTED', 'Tentatively Accepted'), ('REVISION_REQUESTED', 'Revision Requested'), ('REVISED_PROPOSAL_SUBMITTED', 'Revised Proposal Submitted'), ('REVISION_DEADLINE_MISSED', 'Revision Deadline Missed'), ('UNDER_STAGE_2_REVIEW', 'Under Stage 2 Review'), ('FINAL_ACCEPTED', 'Final Accepted'), ('FINAL_REJECTED', 'Final Rejected')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_deadline', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='proposals.grantcycle')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage1Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('REJECT', 'Reject'), ('ACCEPT', 'Accept (No Corrections Required)'), ('TENTATIVELY_ACCEPT', 'Tentatively Accept (Revision Required)')], max_length=30)),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('chair_comments', models.TextField(blank=True, help_text='Optional comments from SRC Chair')),
                ('average_score', models.DecimalField(decimal_places=2, help_text='Average percentage score from all Stage 1 reviews', max_digits=5)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage1_decision', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Stage 1 Decision',
                'verbose_name_plural': 'Stage 1 Decisions',
            },
        ),
    ]
