# Generated by Django - Performance optimization indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_initial'),
    ]

    operations = [
        # Proposal indexes for common queries
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='proposal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['cycle', 'status'], name='proposal_cycle_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['pi', 'status'], name='proposal_pi_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['-created_at'], name='proposal_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['-submitted_at'], name='proposal_submitted_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['revision_deadline'], name='proposal_revision_deadline_idx'),
        ),

        # GrantCycle indexes
        migrations.AddIndex(
            model_name='grantcycle',
            index=models.Index(fields=['is_active'], name='cycle_active_idx'),
        ),
        migrations.AddIndex(
            model_name='grantcycle',
            index=models.Index(fields=['-year'], name='cycle_year_desc_idx'),
        ),
    ]
