# Generated by Django 4.2.28 on 2026-02-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='grantcycle',
            name='cycle_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='grantcycle',
            name='cycle_year_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='proposal_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='proposal_cycle_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='proposal_pi_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='proposal_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='proposal_submitted_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='proposal_revision_deadline_idx',
        ),
    ]
