# Generated by Django 4.2.28 on 2026-02-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_remove_grantcycle_cycle_active_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='pi',
        ),
    ]
