# Generated by Django 4.2.28 on 2026-02-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_remove_proposal_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked after final decision'),
        ),
    ]
