# Generated by Django 4.2.28 on 2026-02-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(1, 'Stage 1 (Initial Evaluation)'), (2, 'Stage 2 (Revision Review)')])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether notification email has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Assignment',
                'verbose_name_plural': 'Review Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_expertise', models.TextField(help_text="Reviewer's area of expertise")),
                ('max_review_load', models.IntegerField(default=5, help_text='Maximum number of concurrent reviews')),
                ('is_active_reviewer', models.BooleanField(default=True, help_text='Whether this reviewer is currently active')),
            ],
            options={
                'verbose_name': 'Reviewer Profile',
                'verbose_name_plural': 'Reviewer Profiles',
            },
        ),
        migrations.CreateModel(
            name='Stage2Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concerns_addressed', models.CharField(choices=[('YES', 'Yes'), ('PARTIALLY', 'Partially'), ('NO', 'No')], help_text='Have Stage 1 concerns been addressed?', max_length=20)),
                ('revised_recommendation', models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject')], help_text='Final recommendation after reviewing revisions', max_length=20)),
                ('revised_score', models.IntegerField(blank=True, help_text='Optional revised score (0-100)', null=True)),
                ('comments', models.TextField(help_text='Comments on the revised proposal')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True, help_text='Whether this is a draft or final submission')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage2_review', to='reviews.reviewassignment')),
            ],
            options={
                'verbose_name': 'Stage 2 Review',
                'verbose_name_plural': 'Stage 2 Reviews',
            },
        ),
        migrations.CreateModel(
            name='Stage1Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality_score', models.IntegerField(default=0, help_text='Originality of the proposed research (0-15)')),
                ('clarity_score', models.IntegerField(default=0, help_text='Clarity and rationality of the research question, thesis, hypotheses (0-15)')),
                ('literature_review_score', models.IntegerField(default=0, help_text='Literature review (assessment of relevant background materials and prior related studies) (0-15)')),
                ('methodology_score', models.IntegerField(default=0, help_text='Appropriateness of the methodology (0-15)')),
                ('impact_score', models.IntegerField(default=0, help_text='Potential impact of research findings/Policy implication/Contribution to existing knowledge (0-15)')),
                ('publication_potential_score', models.IntegerField(default=0, help_text='Potential for publication/dissemination of research results (0-10)')),
                ('budget_appropriateness_score', models.IntegerField(default=0, help_text='Appropriateness of the proposed budget (0-10)')),
                ('timeline_practicality_score', models.IntegerField(default=0, help_text='Practicality of the proposed time frame (0-5)')),
                ('narrative_comments', models.TextField(help_text='Detailed narrative comments from reviewer')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True, help_text='Whether this is a draft or final submission')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage1_score', to='reviews.reviewassignment')),
            ],
            options={
                'verbose_name': 'Stage 1 Score',
                'verbose_name_plural': 'Stage 1 Scores',
            },
        ),
    ]
