# Generated by Django - Performance optimization indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        # ReviewAssignment indexes for common queries
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['reviewer', 'status'], name='review_reviewer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['proposal', 'stage'], name='review_proposal_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['status'], name='review_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['deadline'], name='review_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['-assigned_date'], name='review_assigned_desc_idx'),
        ),
    ]
