# Generated by Django 4.2.28 on 2026-02-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewassignment',
            name='review_reviewer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewassignment',
            name='review_proposal_stage_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewassignment',
            name='review_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewassignment',
            name='review_deadline_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewassignment',
            name='review_assigned_desc_idx',
        ),
    ]
